"""empty message

Revision ID: aab775e18337
Revises: b1b82865b2c5
Create Date: 2025-01-28 11:09:30.434275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab775e18337'
down_revision = 'b1b82865b2c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('booking_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['service_provider.service_provider_id'], name=op.f('fk_booking_provider_id_service_provider')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_booking_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###
